apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "heimdall.fullname" . }}
webhooks:
  - name: {{ include "heimdall.fullname" . }}.{{ .Release.Namespace }}.svc
    clientConfig:
      service:
        name: {{ include "heimdall.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
      #caBundle: 
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]